alias halt='echo Disabled. Use full path to overwrite'
alias shutdown='echo Disabled. Use full path to overwrite'
alias poweroff='echo Disabled. Use full path to overwrite'
alias reboot='echo Disabled. Use full path to overwrite'
alias openencrypteddrive='cryptsetup luksOpen /dev/sda ftp && mount -o rw,noexec,nosuid,nodev /dev/mapper/ftp /var/ftp'
